from django.db import models
from django.contrib.auth.models import User
import csv

from xlrd import open_workbook

# Create your models here.
class Team(models.Model):

    TEAM_OPTIONS = (
        ("T1", "Mclaughlin/Albertine"),
        ("T2", "Johnson/Elizondo"),
        ("T3", "Charles/Trey"),
        ("T4", "Elrod/Vinings"),
        ("T5", "Cummins/Reynolds"),
        ("T6", "J Harris/White"),
        ("T7", "Spurs/Dempster"),
        ("T8", "Tice/Marino"),
        ("T9", "Weston/Jagar"),
        ("T10", "Hooper/Allison/Tummins"),
        ("T11", "Whitten/Jordan/Cain"),
        ("T12", "Snow/Hennigan/Paslick"),
        ("T13", "Bill/Tim"),
        ("T14", "Gooding/Gangl"),
        ("T15", "Hall/Szwilski"),
        ("T15", "Long/Capooth"),
        ("T15", "Dunn/Wilson"),
        ("T15", "Stiles/Martin"),
        ("T15", "Preston/Farmer/Hendricks"),
        ("T15", "Gilpin/Dunn"),
        ("T15", "Team Test"),
        )

    name = models.CharField(max_length=200, choices=TEAM_OPTIONS, verbose_name='Team', null=True, blank=True)
    memberone = models.OneToOneField(User, on_delete=models.CASCADE,related_name='+', null=True, blank=True)
    membertwo = models.OneToOneField(User, on_delete=models.CASCADE, related_name='+', null=True, blank=True)
    score = models.DecimalField(max_digits=19, decimal_places=2, null=True, blank=True)
    description = models.TextField(max_length=1024)
#    logo = models.ImageField()






class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    team = models.ForeignKey('team', on_delete=models.CASCADE, related_name='+')



class Golfers(models.Model):
    GOLFER_LIST = (
        ("Aaron Baddeley","Aaron Baddeley"),
        ("Aaron Wise","Aaron Wise"),
        ("Abraham Ancer","Abraham Ancer"),
        ("Adam Hadwin","Adam Hadwin"),
        ("Adam Schenk","Adam Schenk"),
        ("Alex Cejka","Alex Cejka"),
        ("Alex Noren","Alex Noren"),
        ("Andrew Landry","Andrew Landry"),
        ("Andrew Loupe","Andrew Loupe"),
        ("Andrew Putnam","Andrew Putnam"),
        ("Andrew Yun","Andrew Yun"),
        ("Anirban Lahiri","Anirban Lahiri"),
        ("Austin Cook","Austin Cook"),
        ("Beau Hossler","Beau Hossler"),
        ("Ben Crane","Ben Crane"),
        ("Ben Martin","Ben Martin"),
        ("Ben Silverman","Ben Silverman"),
        ("Bill Haas","Bill Haas"),
        ("Billy Horschel","Billy Horschel"),
        ("Billy Hurley III","Billy Hurley III"),
        ("Blayne Barber","Blayne Barber"),
        ("Brandon Hagy","Brandon Hagy"),
        ("Brandon Harkins","Brandon Harkins"),
        ("Brandt Snedeker","Brandt Snedeker"),
        ("Brendan Steele","Brendan Steele"),
        ("Brendon de Jonge","Brendon de Jonge"),
        ("Brett Stegmaier","Brett Stegmaier"),
        ("Brian Davis","Brian Davis"),
        ("Brian Gay","Brian Gay"),
        ("Brian Harman","Brian Harman"),
        ("Brian Stuard","Brian Stuard"),
        ("Brice Garnett","Brice Garnett"),
        ("Bronson Burgoon","Bronson Burgoon"),
        ("Brooks Koepka","Brooks Koepka"),
        ("Bryson DeChambeau","Bryson DeChambeau"),
        ("Bubba Watson","Bubba Watson"),
        ("Bud Cauley","Bud Cauley"),
        ("Byeong Hun An","Byeong Hun An"),
        ("C.T. Pan","C.T. Pan"),
        ("Cameron Percy","Cameron Percy"),
        ("Cameron Smith","Cameron Smith"),
        ("Cameron Tringale","Cameron Tringale"),
        ("Camilo Villegas","Camilo Villegas"),
        ("Chad Campbell","Chad Campbell"),
        ("Charles Howell III","Charles Howell III"),
        ("Charley Hoffman","Charley Hoffman"),
        ("Charlie Beljan","Charlie Beljan"),
        ("Chesson Hadley","Chesson Hadley"),
        ("Chez Reavie","Chez Reavie"),
        ("Chris Kirk","Chris Kirk"),
        ("Chris Stroud","Chris Stroud"),
        ("Cody Gribble","Cody Gribble"),
        ("Colt Knost","Colt Knost"),
        ("Conrad Shindler","Conrad Shindler"),
        ("Corey Conners","Corey Conners"),
        ("D.A. Points","D.A. Points"),
        ("Daisuke Kataoka","Daisuke Kataoka"),
        ("Daniel Berger","Daniel Berger"),
        ("Daniel Summerhays","Daniel Summerhays"),
        ("Danny Lee","Danny Lee"),
        ("David Hearn","David Hearn"),
        ("David Lingmerth","David Lingmerth"),
        ("Davis Love III","Davis Love III"),
        ("Denny McCarthy","Denny McCarthy"),
        ("Derek Fathauer","Derek Fathauer"),
        ("Dominic Bozzelli","Dominic Bozzelli"),
        ("Dustin Johnson","Dustin Johnson"),
        ("Emiliano Grillo","Emiliano Grillo"),
        ("Ernie Els","Ernie Els"),
        ("Ethan Tracy","Ethan Tracy"),
        ("Fabián Gómez","Fabián Gómez"),
        ("Francesco Molinari","Francesco Molinari"),
        ("Gary Woodland","Gary Woodland"),
        ("Geoff Ogilvy","Geoff Ogilvy"),
        ("Graeme McDowell","Graeme McDowell"),
        ("Graham DeLaet","Graham DeLaet"),
        ("Grayson Murray","Grayson Murray"),
        ("Greg Chalmers","Greg Chalmers"),
        ("Harold Varner III","Harold Varner III"),
        ("Harris English","Harris English"),
        ("Hideki Matsuyama","Hideki Matsuyama"),
        ("Hudson Swafford","Hudson Swafford"),
        ("Hunter Mahan","Hunter Mahan"),
        ("Ian Poulter","Ian Poulter"),
        ("J.B. Holmes","J.B. Holmes"),
        ("J.J. Henry","J.J. Henry"),
        ("J.J. Spaun","J.J. Spaun"),
        ("J.T. Poston","J.T. Poston"),
        ("James Hahn","James Hahn"),
        ("Jamie Lovemark","Jamie Lovemark"),
        ("Jason Day","Jason Day"),
        ("Jason Dufner","Jason Dufner"),
        ("Jason Kokrak","Jason Kokrak"),
        ("Jhonattan Vegas","Jhonattan Vegas"),
        ("Jim Herman","Jim Herman"),
        ("Jimmy Walker","Jimmy Walker"),
        ("Joel Dahmen","Joel Dahmen"),
        ("John Daly","John Daly"),
        ("John Huh","John Huh"),
        ("John Oda","John Oda"),
        ("John Peterson","John Peterson"),
        ("Johnson Wagner","Johnson Wagner"),
        ("Jon Curran","Jon Curran"),
        ("Jon Rahm","Jon Rahm"),
        ("Jonas Blixt","Jonas Blixt"),
        ("Jonathan Byrd","Jonathan Byrd"),
        ("Jonathan Randolph","Jonathan Randolph"),
        ("Jordan Spieth","Jordan Spieth"),
        ("Justin Rose","Justin Rose"),
        ("Justin Thomas","Justin Thomas"),
        ("K.J. Choi","K.J. Choi"),
        ("Keegan Bradley","Keegan Bradley"),
        ("Keith Mitchell","Keith Mitchell"),
        ("Kelly Kraft","Kelly Kraft"),
        ("Ken Duke","Ken Duke"),
        ("Kevin Chappell","Kevin Chappell"),
        ("Kevin Kisner","Kevin Kisner"),
        ("Kevin Na","Kevin Na"),
        ("Kevin Streelman","Kevin Streelman"),
        ("Kevin Tway","Kevin Tway"),
        ("Kyle Stanley","Kyle Stanley"),
        ("Kyle Thompson","Kyle Thompson"),
        ("Lanto Griffin","Lanto Griffin"),
        ("Lucas Glover","Lucas Glover"),
        ("Luke Donald","Luke Donald"),
        ("Luke List","Luke List"),
        ("Mac Hughes","Mac Hughes"),
        ("Marc Leishman","Marc Leishman"),
        ("Mark Wilson","Mark Wilson"),
        ("Martin Flores","Martin Flores"),
        ("Martin Laird","Martin Laird"),
        ("Martin Piller","Martin Piller"),
        ("Matt Atkins","Matt Atkins"),
        ("Matt Every","Matt Every"),
        ("Matt Jones","Matt Jones"),
        ("Matt Kuchar","Matt Kuchar"),
        ("Maverick McNealy","Maverick McNealy"),
        ("Michael Kim","Michael Kim"),
        ("Michael Thompson","Michael Thompson"),
        ("Morgan Hoffmann","Morgan Hoffmann"),
        ("Nate Lashley","Nate Lashley"),
        ("Nicholas Lindheim","Nicholas Lindheim"),
        ("Nick Taylor","Nick Taylor"),
        ("Nick Watney","Nick Watney"),
        ("Ollie Schniederjans","Ollie Schniederjans"),
        ("Pat Perez","Pat Perez"),
        ("Patrick Cantlay","Patrick Cantlay"),
        ("Patrick Reed","Patrick Reed"),
        ("Patrick Rodgers","Patrick Rodgers"),
        ("Patton Kizzire","Patton Kizzire"),
        ("Peter Malnati","Peter Malnati"),
        ("Peter Uihlein","Peter Uihlein"),
        ("Phil Mickelson","Phil Mickelson"),
        ("Retief Goosen","Retief Goosen"),
        ("Richy Werenski","Richy Werenski"),
        ("Rick Lamb","Rick Lamb"),
        ("Rickie Fowler","Rickie Fowler"),
        ("Ricky Barnes","Ricky Barnes"),
        ("Rob Oppenheim","Rob Oppenheim"),
        ("Robert Garrigus","Robert Garrigus"),
        ("Robert Streb","Robert Streb"),
        ("Roberto Díaz","Roberto Díaz"),
        ("Rod Pampling","Rod Pampling"),
        ("Rory Sabbatini","Rory Sabbatini"),
        ("Russell Henley","Russell Henley"),
        ("Russell Knox","Russell Knox"),
        ("Ryan Armour","Ryan Armour"),
        ("Ryan Blaum","Ryan Blaum"),
        ("Ryan Moore","Ryan Moore"),
        ("Ryan Palmer","Ryan Palmer"),
        ("Sam Burns","Sam Burns"),
        ("Sam Ryder","Sam Ryder"),
        ("Sam Saunders","Sam Saunders"),
        ("Sangmoon Bae","Sangmoon Bae"),
        ("Scott Brown","Scott Brown"),
        ("Scott Piercy","Scott Piercy"),
        ("Scott Stallings","Scott Stallings"),
        ("Seamus Power","Seamus Power"),
        ("Sean O'Hair","Sean O'Hair"),
        ("Shawn Stefani","Shawn Stefani"),
        ("Si Woo Kim","Si Woo Kim"),
        ("Smylie Kaufman","Smylie Kaufman"),
        ("Stephan Jaeger","Stephan Jaeger"),
        ("Steve Wheatcroft","Steve Wheatcroft"),
        ("Stewart Cink","Stewart Cink"),
        ("Sung Kang","Sung Kang"),
        ("Talor Gooch","Talor Gooch"),
        ("Ted Potter, Jr.","Ted Potter, Jr."),
        ("Tom Hoge","Tom Hoge"),
        ("Tom Lovelady","Tom Lovelady"),
        ("Tony Finau","Tony Finau"),
        ("Trey Mullinax","Trey Mullinax"),
        ("Troy Merritt","Troy Merritt"),
        ("Tyler Duncan","Tyler Duncan"),
        ("Tyrone Van Aswegen","Tyrone Van Aswegen"),
        ("Vaughn Taylor","Vaughn Taylor"),
        ("Webb Simpson","Webb Simpson"),
        ("Wesley Bryan","Wesley Bryan"),
        ("Whee Kim","Whee Kim"),
        ("William McGirt","William McGirt"),
        ("Wyndham Clark","Wyndham Clark"),
        ("Xander Schauffele","Xander Schauffele"),
        ("Xinjun Zhang","Xinjun Zhang"),
        ("Zac Blair","Zac Blair"),
        ("Zach Johnson","Zach Johnson"),
        ("Zecheng Dou","Zecheng Dou"),
        )


    golferName = models.CharField(max_length=200, choices=GOLFER_LIST, verbose_name='Team', null=True, blank=True)

    teamselection = models.ForeignKey('team', on_delete=models.CASCADE, related_name='golfersel',null=True, blank=True)

    def publish(self):

        self.save()

    def __str__(self):
        return self.golferName
        return self.teamselection
