# Generated by Django 2.0.2 on 2018-02-09 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('T1', 'Mclaughlin/Albertine'), ('T2', 'Johnson/Elizondo'), ('T3', 'Charles/Trey'), ('T4', 'Elrod/Vinings'), ('T5', 'Cummins/Reynolds'), ('T6', 'J Harris/White'), ('T7', 'Spurs/Dempster'), ('T8', 'Tice/Marino'), ('T9', 'Weston/Jagar'), ('T10', 'Hooper/Allison/Tummins'), ('T11', 'Whitten/Jordan/Cain'), ('T12', 'Snow/Hennigan/Paslick'), ('T13', 'Bill/Tim'), ('T14', 'Gooding/Gangl'), ('T15', 'Hall/Szwilski'), ('T15', 'Long/Capooth'), ('T15', 'Dunn/Wilson'), ('T15', 'Stiles/Martin'), ('T15', 'Preston/Farmer/Hendricks'), ('T15', 'Gilpin/Dunn'), ('T15', 'Team Test')], max_length=200, null=True, verbose_name='Team')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('description', models.TextField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
