# Generated by Django 2.0.2 on 2018-02-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180209_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Golfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
