# Generated by Django 2.0.2 on 2018-02-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_golfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfers',
            name='golf_selection',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Team'),
        ),
    ]
