# Generated by Django 2.0.2 on 2018-02-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_golfers_golf_selection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfers',
            name='golf_selection',
        ),
    ]
