# Generated by Django 2.0.2 on 2018-02-09 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_golfers_golfer_selection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golfers',
            old_name='golfer_selection',
            new_name='selection',
        ),
    ]
