# Generated by Django 2.0.2 on 2018-02-09 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180209_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfers',
            name='teamselection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Team'),
        ),
    ]
