# Generated by Django 2.0.2 on 2018-02-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180209_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfers',
            name='golferwinnings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
