# Generated by Django 2.0.2 on 2018-02-10 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_golfers_golferwinnings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golfers',
            old_name='selection',
            new_name='golferName',
        ),
    ]
